import streamlit as st
from auth import require_admin
require_admin()
from datetime import datetime
import uuid
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER

from work_order_database import create_work_order


# =====================================================
# GENERATE WORK ORDER PDF
# =====================================================

def generate_work_order_pdf(
    work_order_id,
    product_id,
    machine_id,
    machine_type,
    technician,
    priority,
    task,
    status,
    created_date
):

    buffer = BytesIO()

    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    normal_style = styles["Normal"]

    elements = []

    elements.append(
        Paragraph(
            "PREDICTIVE MAINTENANCE SYSTEM",
            title_style
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    elements.append(
        Paragraph(
            "MAINTENANCE WORK ORDER",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 15)
    )

    data = [

        ["Work Order ID", work_order_id],

        ["Product ID", product_id],

        ["Machine ID (UDI)", str(machine_id)],

        ["Machine Type", machine_type],

        ["Assigned Technician", technician],

        ["Priority", priority],

        ["Status", status],

        ["Created Date", created_date],

        ["Maintenance Task", task]

    ]

    table = Table(
        data,
        colWidths=[170, 330]
    )

    table.setStyle(

        TableStyle(

            [

                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.lightgrey
                ),

                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.grey
                ),

                (
                    "FONTNAME",
                    (0, 0),
                    (0, -1),
                    "Helvetica-Bold"
                ),

                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP"
                ),

                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    8
                ),

                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    8
                ),

                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    8
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    8
                )

            ]

        )

    )

    elements.append(table)

    elements.append(
        Spacer(1, 30)
    )

    elements.append(
        Paragraph(
            "This work order was generated by the Predictive Maintenance System.",
            normal_style
        )
    )

    document.build(elements)

    buffer.seek(0)

    return buffer


# =====================================================
# PAGE CONFIGURATION
# =====================================================

st.set_page_config(

    page_title="Work Order Creation",

    page_icon="📝",

    layout="wide"

)


# =====================================================
# PROFESSIONAL UI
# =====================================================

st.markdown(

    """
    <style>

    .main-title {

        font-size: 36px;

        font-weight: 700;

        margin-bottom: 5px;

    }

    .subtitle {

        font-size: 16px;

        opacity: 0.7;

        margin-bottom: 25px;

    }

    .section-header {

        font-size: 22px;

        font-weight: 600;

        margin-top: 20px;

        margin-bottom: 15px;

    }

    </style>

    """,

    unsafe_allow_html=True

)


# =====================================================
# PAGE HEADER
# =====================================================

st.markdown(

    '<div class="main-title">'
    '📝 Work Order Creation'
    '</div>',

    unsafe_allow_html=True

)


st.markdown(

    '<div class="subtitle">'
    'Create, store, and download maintenance work orders.'
    '</div>',

    unsafe_allow_html=True

)


# =====================================================
# CHECK SELECTED MACHINE
# =====================================================

if "selected_machine" not in st.session_state:

    st.warning(

        "⚠️ Please select a machine first from the Machine Explorer."

    )

    st.stop()


# =====================================================
# GET SELECTED MACHINE
# =====================================================

machine = st.session_state["selected_machine"]


# =====================================================
# SELECTED MACHINE INFORMATION
# =====================================================

st.markdown("---")


st.markdown(

    '<div class="section-header">'
    '🏭 Selected Machine'
    '</div>',

    unsafe_allow_html=True

)


col1, col2, col3, col4 = st.columns(4)


col1.metric(

    "Product ID",

    machine["Product ID"]

)


col2.metric(

    "Machine ID",

    machine["UDI"]

)


col3.metric(

    "Machine Type",

    machine["Type"]

)


if machine["Machine failure"] == 1:

    col4.error(

        "⚠ FAILED"

    )

else:

    col4.success(

        "✅ NORMAL"

    )


# =====================================================
# GENERATE WORK ORDER ID
# =====================================================

work_order_id = (

    "WO-"

    + datetime.now().strftime(
        "%Y%m%d%H%M%S"
    )

    + "-"

    + str(uuid.uuid4())[:4].upper()

)


# =====================================================
# WORK ORDER FORM
# =====================================================

st.markdown("---")


st.markdown(

    '<div class="section-header">'
    '📝 Maintenance Work Order'
    '</div>',

    unsafe_allow_html=True

)


st.info(

    f"🆔 Work Order ID: **{work_order_id}**"

)


# =====================================================
# FORM LAYOUT
# =====================================================

form_col1, form_col2 = st.columns(2)


with form_col1:

    technician = st.selectbox(

        "👨‍🔧 Assign Technician",

        [

            "Select Technician",

            "Arun",

            "Kumar",

            "Priya",

            "Meena"

        ]

    )


with form_col2:

    priority = st.selectbox(

        "⚠ Select Priority",

        [

            "Low",

            "Medium",

            "High",

            "Critical"

        ]

    )


# =====================================================
# DEFAULT MAINTENANCE TASK
# =====================================================

if machine["Machine failure"] == 1:

    default_task = (

        "Immediate maintenance required. "
        "Check detected machine failure components."

    )

elif machine["Tool wear [min]"] > 150:

    default_task = (

        "Perform preventive maintenance "
        "because of high tool wear."

    )

else:

    default_task = (

        "Perform routine machine inspection."

    )


# =====================================================
# MAINTENANCE TASK
# =====================================================

task = st.text_area(

    "🛠 Maintenance Task",

    value=default_task,

    height=150

)


# =====================================================
# CREATE WORK ORDER
# =====================================================

st.markdown("---")


create_button = st.button(

    "📝 Create Work Order",

    type="primary",

    width="stretch"

)


if create_button:

    if technician == "Select Technician":

        st.warning(

            "⚠️ Please select a technician."

        )


    elif task.strip() == "":

        st.warning(

            "⚠️ Please enter a maintenance task."

        )


    else:

        # =================================================
        # CREATED DATE
        # =================================================

        created_date = datetime.now().strftime(

            "%Y-%m-%d %H:%M:%S"

        )


        # =================================================
        # SAVE WORK ORDER TO SQLITE DATABASE
        # =================================================

        create_work_order(

            work_order_id=work_order_id,

            product_id=machine["Product ID"],

            machine_id=int(machine["UDI"]),

            machine_type=machine["Type"],

            technician=technician,

            priority=priority,

            task=task,

            status="Assigned",

            created_date=created_date

        )


        # =================================================
        # SUCCESS MESSAGE
        # =================================================

        st.success(

            "✅ Work order created successfully "
            "and saved to the database."

        )


        # =================================================
        # GENERATE PDF
        # =================================================

        pdf_file = generate_work_order_pdf(

            work_order_id=work_order_id,

            product_id=machine["Product ID"],

            machine_id=int(machine["UDI"]),

            machine_type=machine["Type"],

            technician=technician,

            priority=priority,

            task=task,

            status="Assigned",

            created_date=created_date

        )


        # =================================================
        # DOWNLOAD PDF
        # =================================================

        st.download_button(

            label="📄 Download Work Order PDF",

            data=pdf_file,

            file_name=f"{work_order_id}.pdf",

            mime="application/pdf",

            width="stretch"

        )


        # =================================================
        # WORK ORDER SUMMARY
        # =================================================

        st.markdown("---")


        st.markdown(

            '<div class="section-header">'
            '📋 Work Order Summary'
            '</div>',

            unsafe_allow_html=True

        )


        summary_col1, summary_col2, summary_col3, summary_col4 = st.columns(4)


        summary_col1.metric(

            "Work Order ID",

            work_order_id

        )


        summary_col2.metric(

            "Machine",

            machine["Product ID"]

        )


        summary_col3.metric(

            "Technician",

            technician

        )


        summary_col4.metric(

            "Status",

            "Assigned"

        )


        st.markdown("---")


        st.info(

            f"""

            **Work Order Created**

            🆔 **ID:** {work_order_id}

            🏭 **Machine:** {machine["Product ID"]}

            👨‍🔧 **Technician:** {technician}

            ⚠ **Priority:** {priority}

            📌 **Status:** Assigned

            🛠 **Task:** {task}

            """

        )